version: '3.9'
services:
  backend:
    build: ./backend
    container_name: back
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    container_name: front
    ports:
      - 3000:3000
    stdin_open: true
    tty: true             
